services:
  - type: web
    name: telegram-forward-bot
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/jairamjiki/Forward-bot
    branch: main
    autoDeploy: true
    envVars:
      - key: API_ID
        value: your_api_id
      - key: API_HASH
        value: your_api_hash
      - key: BOT_TOKEN
        value: your_bot_token
      - key: MONGO_URL
        value: your_mongo_uri
      - key: OWNER_ID
        value: your_owner_id
      - key: PORT
        value: 10000
